# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'placing_order.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(575, 299)
        self.cart = QtWidgets.QListWidget(Dialog)
        self.cart.setGeometry(QtCore.QRect(280, 30, 291, 211))
        self.cart.setObjectName("cart")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 40, 57, 15))
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(260, 0, 20, 301))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(370, 10, 80, 20))
        font = QtGui.QFont()
        font.setFamily("padmaa-Bold.1.1")
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.CB = QtWidgets.QComboBox(Dialog)
        self.CB.setGeometry(QtCore.QRect(60, 30, 201, 31))
        self.CB.setObjectName("CB")
        self.CB.addItem("")
        self.CB.addItem("")
        self.CB.addItem("")
        self.CB.addItem("")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 30, 15))
        self.label_3.setObjectName("label_3")
        self.SB = QtWidgets.QSpinBox(Dialog)
        self.SB.setGeometry(QtCore.QRect(60, 80, 61, 31))
        self.SB.setObjectName("SB")
        self.add_product = QtWidgets.QPushButton(Dialog)
        self.add_product.setGeometry(QtCore.QRect(90, 120, 90, 26))
        self.add_product.setObjectName("add_product")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(40, 180, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.LCD_total = QtWidgets.QLCDNumber(Dialog)
        self.LCD_total.setGeometry(QtCore.QRect(140, 170, 81, 31))
        self.LCD_total.setObjectName("LCD_total")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(120, 170, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(0, 150, 271, 20))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 210, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(120, 210, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.LCD_discount = QtWidgets.QLCDNumber(Dialog)
        self.LCD_discount.setGeometry(QtCore.QRect(140, 210, 81, 31))
        self.LCD_discount.setObjectName("LCD_discount")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(30, 260, 60, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(120, 260, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.LCD_to_pay = QtWidgets.QLCDNumber(Dialog)
        self.LCD_to_pay.setGeometry(QtCore.QRect(140, 260, 81, 31))
        self.LCD_to_pay.setObjectName("LCD_to_pay")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(0, 240, 271, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line_3.setFont(font)
        self.line_3.setAutoFillBackground(False)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.edit = QtWidgets.QPushButton(Dialog)
        self.edit.setGeometry(QtCore.QRect(280, 260, 80, 26))
        self.edit.setObjectName("edit")
        self.Del_all = QtWidgets.QPushButton(Dialog)
        self.Del_all.setGeometry(QtCore.QRect(480, 260, 80, 26))
        self.Del_all.setObjectName("Del_all")
        self.Del = QtWidgets.QPushButton(Dialog)
        self.Del.setGeometry(QtCore.QRect(380, 260, 80, 26))
        self.Del.setObjectName("Del")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Product: "))
        self.label_2.setText(_translate("Dialog", "My Cart"))
        self.CB.setItemText(0, _translate("Dialog", "Pasta Sauce            -> $ 2.99"))
        self.CB.setItemText(1, _translate("Dialog", "2 x Oranges            -> $ 0.49 "))
        self.CB.setItemText(2, _translate("Dialog", "Lays Chips (Spicy)  -> $ 0.49"))
        self.CB.setItemText(3, _translate("Dialog", "Coconut Biscuits     -> $ 0.99 "))
        self.label_3.setText(_translate("Dialog", "Qty: "))
        self.add_product.setText(_translate("Dialog", "Add Product"))
        self.label_4.setText(_translate("Dialog", "Total: "))
        self.label_5.setText(_translate("Dialog", "$"))
        self.label_6.setText(_translate("Dialog", "10% Discount: "))
        self.label_7.setText(_translate("Dialog", "$"))
        self.label_8.setText(_translate("Dialog", "To Pay:"))
        self.label_9.setText(_translate("Dialog", "$"))
        self.edit.setText(_translate("Dialog", "Edit"))
        self.Del_all.setText(_translate("Dialog", "Delete All"))
        self.Del.setText(_translate("Dialog", "Delete"))
